import { Workspace, WorkspaceData, Repository, PackageLink, RepositoryWithPackages } from './types';
import { getWorkspaces as getDummyWorkspaces, getWorkspaceData as getDummyWorkspaceData } from '../data/workspaceData';
import { getRepositoryData } from '../data/packageRegistry';

/**
 * Workspace Service Layer
 * 
 * To integrate with Tauri:
 * Replace the implementation of each function with:
 * return await invoke('command_name', { ...params });
 */

// In-memory storage for workspace-specific data created from templates
const workspaceDataStore: Map<string, Partial<WorkspaceData>> = new Map();

/**
 * Get all workspaces
 * 
 * Tauri command: invoke('get_workspaces')
 */
export async function getWorkspaces(): Promise<Workspace[]> {
  // Simulate async operation
  await new Promise(resolve => setTimeout(resolve, 50));
  return getDummyWorkspaces();
}

/**
 * Get workspace data including repositories, PRs, activities, and packages
 * 
 * Tauri command: invoke('get_workspace_data', { workspaceId })
 */
export async function getWorkspaceData(workspaceId: string): Promise<WorkspaceData> {
  // Simulate async operation
  await new Promise(resolve => setTimeout(resolve, 50));
  
  // Check if we have template data for this workspace
  const templateData = workspaceDataStore.get(workspaceId);
  
  if (templateData) {
    // Get default data for PRs and activities (which templates don't include)
    const defaultData = getDummyWorkspaceData(workspaceId);
    const result = {
      repositories: templateData.repositories || defaultData.repositories,
      packageLinks: templateData.packageLinks || defaultData.packageLinks,
      packageRepositories: templateData.packageRepositories || defaultData.packageRepositories,
      pullRequests: defaultData.pullRequests,
      activities: defaultData.activities,
    };
    return result;
  }
  
  return getDummyWorkspaceData(workspaceId);
}

/**
 * Create a new workspace
 * 
 * Tauri command: invoke('create_workspace', { name })
 * The path is automatically generated by nut
 */
export async function createWorkspace(name: string): Promise<Workspace> {
  // Simulate async operation
  await new Promise(resolve => setTimeout(resolve, 100));
  
  // In Tauri, the path will be auto-generated by nut
  // For demo purposes, we'll generate a mock path
  const mockPath = `/workspaces/${name.toLowerCase().replace(/\s+/g, '-')}`;
  
  const newWorkspace: Workspace = {
    id: Date.now().toString(),
    name,
    path: mockPath,
    createdAt: new Date().toISOString(),
  };
  
  return newWorkspace;
}

/**
 * Delete a workspace
 * 
 * Tauri command: invoke('delete_workspace', { workspaceId })
 */
export async function deleteWorkspace(workspaceId: string): Promise<void> {
  // Simulate async operation
  await new Promise(resolve => setTimeout(resolve, 100));
}

/**
 * Rename a workspace
 * \n * Tauri command: invoke('rename_workspace', { workspaceId, newName })
 */
export async function renameWorkspace(workspaceId: string, newName: string): Promise<void> {
  // Simulate async operation
  await new Promise(resolve => setTimeout(resolve, 100));
}

/**
 * Apply template data to a workspace
 * This is called after creating a workspace from a template
 * 
 * Tauri: This will be handled by the backend when creating from template
 */
export async function applyTemplateToWorkspace(
  workspaceId: string,
  repositories: Array<{ owner: string; name: string }>,
  links: PackageLink[]
): Promise<void> {
  // Convert template repos to Repository objects with default values
  const repoObjects: Repository[] = repositories.map(repo => ({
    name: repo.name,
    owner: repo.owner,
    branch: 'main',
    status: 'clean' as const,
    url: `https://github.com/${repo.owner}/${repo.name}`,
  }));

  // Convert template repos to RepositoryWithPackages
  // Try to get package data from the registry, fallback to empty
  const packageRepos: RepositoryWithPackages[] = repositories.map(repo => {
    const repoFullName = `${repo.owner}/${repo.name}`;
    const registryData = getRepositoryData(repoFullName);
    
    if (registryData) {
      return registryData;
    }
    
    // Fallback if not in registry
    return {
      name: repo.name,
      owner: repo.owner,
      packages: [],
    };
  });

  // Activate all links from the template (set status to 'linked')
  const activatedLinks = links.map(link => ({
    ...link,
    status: 'linked' as const,
  }));

  const dataToStore = {
    repositories: repoObjects,
    packageLinks: activatedLinks,
    packageRepositories: packageRepos,
  };
  
  workspaceDataStore.set(workspaceId, dataToStore);
  
  // Small delay to ensure data is stored before any reads
  await new Promise(resolve => setTimeout(resolve, 10));
}