[package]
name = "nut-core"
version.workspace = true
edition.workspace = true
description = "Core library for nut workspace manager"
license-file.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
chrono.workspace = true
config.workspace = true
directories.workspace = true
futures-util.workspace = true
miette.workspace = true
octocrab.workspace = true
serde.workspace = true
serde_json.workspace = true
specta = { version = "2.0.0-rc.20", features = ["derive"], optional = true }
thiserror.workspace = true
tokio.workspace = true
ulid.workspace = true
walkdir.workspace = true

[features]
default = []
typescript = ["specta"]

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
serial_test = "3"
