name: Formatting
permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6d9817901c499d6b02debbb57edb38d33daa680b # stable
        with:
          components: rustfmt
      
      - name: Check formatting
        run: cargo fmt --all --check
